In [2]:
import numpy as np

In [3]:
np.arange(10,32)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [4]:
np.arange(10,91,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,1,5) #~ gives evenly spaces elements with the third parameter be the number of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.rand(2,4) #~gives random positive array filled according to the size of the array 

array([[0.57266807, 0.83710735, 0.31460189, 0.68949342],
       [0.07796713, 0.96271527, 0.08139641, 0.9125404 ]])

In [15]:
np.random.randn(2,4) #~ gives array of given size with elements including positive and negitive too

array([[ 1.27291112, -0.25212169, -0.43422992,  2.97299265],
       [ 1.57779596, -0.55314022, -0.63186809,  1.29672584]])

In [18]:
np.random.randint(0,10,15) #* gives the array filled with random integer with parameters (starting int,ending int, size) 

array([4, 2, 5, 3, 6, 6, 9, 3, 7, 7, 2, 3, 5, 4, 3])

In [21]:
np.eye(6) #^ gives an array with the diagonals being 1 and every else element as 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [74]:
sample_array = np.arange(2,20)

In [75]:
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [76]:
sample_array.min()

2

In [77]:
sample_array.argmin()

0

In [78]:
sample_array.argmax()

17

In [79]:
a= sample_array

In [80]:
a.T

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [83]:
a.reshape(3,6)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [70]:
a = np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [84]:
a[2:10]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

# 2D Matrix

In [89]:
sample_matrix= np.array([
    [24,13,2,15],
    [15,2,54,65],
    [56,76,24,7]
])

In [90]:
sample_matrix[2][2]

24

In [92]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [94]:
sample_matrix[2]

array([56, 76, 24,  7])

In [95]:
np.square(sample_array)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
       225, 256, 289, 324, 361], dtype=int32)

In [96]:
np.std(sample_array)

5.188127472091127

In [97]:
np.var(sample_array)

26.916666666666668

# Pandas

In [98]:
import pandas as pd

In [99]:
sports1 = pd.Series([11,12,13,11],index=['football','cricket','rugby','golf'])

In [100]:
sports1

football    11
cricket     12
rugby       13
golf        11
dtype: int64

In [101]:
sports2 = pd.Series([41,32,11,13],index=['football','cricket','rugby','golf'])


In [102]:
sports1+sports2

football    52
cricket     44
rugby       24
golf        24
dtype: int64

In [106]:
df1 = pd.DataFrame(np.random.rand(8,5),index = 'A B C D E F G H'.split(),columns='col1 col2 col3 col4 col5'.split())
df1

col1      col2      col3      col4      col5
A  0.068452  0.258915  0.946591  0.737066  0.359320
B  0.280594  0.963608  0.790829  0.698891  0.918984
C  0.517148  0.036676  0.829024  0.637675  0.706388
D  0.391681  0.283998  0.437578  0.976295  0.603942
E  0.798634  0.014097  0.945721  0.260023  0.827280
F  0.127569  0.107155  0.382887  0.705008  0.795730
G  0.287991  0.128671  0.728180  0.047440  0.202357
H  0.610831  0.287611  0.130167  0.240107  0.602966

In [108]:
df1.drop('col1',axis=1)

col2      col3      col4      col5
A  0.258915  0.946591  0.737066  0.359320
B  0.963608  0.790829  0.698891  0.918984
C  0.036676  0.829024  0.637675  0.706388
D  0.283998  0.437578  0.976295  0.603942
E  0.014097  0.945721  0.260023  0.827280
F  0.107155  0.382887  0.705008  0.795730
G  0.128671  0.728180  0.047440  0.202357
H  0.287611  0.130167  0.240107  0.602966

In [109]:
df1['col6'] = df1['col4']+df1['col5']

In [111]:
df1

col1      col2      col3      col4      col5      col6
A  0.068452  0.258915  0.946591  0.737066  0.359320  1.096387
B  0.280594  0.963608  0.790829  0.698891  0.918984  1.617875
C  0.517148  0.036676  0.829024  0.637675  0.706388  1.344063
D  0.391681  0.283998  0.437578  0.976295  0.603942  1.580237
E  0.798634  0.014097  0.945721  0.260023  0.827280  1.087304
F  0.127569  0.107155  0.382887  0.705008  0.795730  1.500737
G  0.287991  0.128671  0.728180  0.047440  0.202357  0.249798
H  0.610831  0.287611  0.130167  0.240107  0.602966  0.843074

In [116]:
df2 = {
    'ID':[101,102,103,107,176],
    'Name':['John','Mercy','Akash','Kavin','Laily'],
    'Profit':[20,54,56,87,123]
}




In [119]:
df = pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Laily     123

In [120]:
df.head()

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Laily     123

In [121]:
# CReate a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [123]:
#Create a null vector of size 10 and 5th value is 1
a=np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [124]:
np.arange(10,66)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [133]:
np.arange(65,9,-1)

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])